on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest
    container: rocker/verse
    steps:
      - uses: actions/checkout@v1
      - run: R -e 'rmarkdown::render("analysis/paper.Rmd")'
      - name: Upload results
        uses: actions/upload-artifact@master
        with:
          name: results
          path: paper.html
      - uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: fboehm/qtl2macrophage
          tag_with_ref: true
          tag_with_sha: true
